[build]
# Directory to change to before starting a build.
# This is where we will look for package.json/.nvmrc/etc.
# If not set, defaults to the root directory.
base = "/app"
publish = ".next"

[context.production.environment]
NEXT_PUBLIC_RPC = "https://api.mainnet-beta.solana.com"

[context.deploy-preview.environment]
NEXT_PUBLIC_RPC = "https://api.devnet.solana.com"

[context.branch-deploy.environment]
NEXT_PUBLIC_RPC = "https://api.devnet.solana.com"
